name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: mkdir build
      run: mkdir build
    - name: cd build
      run: cd build && cmake ../
    - name: cd build && make
      run: cd build && make 
